"""Comprehensive unit test suite for ShopiFyX Plain-Text Customer Email Standardization.

Covers all 16 required test scenarios:
1. Simple product question
2. Order-status question
3. Refund request
4. Return request
5. Warranty question
6. Angry customer
7. Follow-up email using 'it', 'that', or 'same issue'
8. Customer with previous conversation history
9. Transactional action successfully initiated
10. Transactional action rejected / policy boundary
11. Escalation response / missing context fallback
12. Missing customer name (Greeting strictly 'Hi,')
13. Response containing Markdown generated by LLM (cleaned to plain text)
14. Response containing excessive blank lines (normalized to \\n\\n)
15. Response containing 'Here is your response:' preamble (stripped)
16. Duplicate greeting / sign-off handling (deduplicated)
"""

from __future__ import annotations

import unittest

from app.agents.decision import validate_email_response
from app.agents.generator import (
    STANDARD_CLOSING,
    _fallback_reply,
    normalize_customer_response,
    sanitize_customer_reply,
)
from app.memory.memory_models import (
    CustomerIssue,
    CustomerMemory,
    CustomerProfile,
)
from app.rag.response_validator import (
    SAFE_FALLBACK_RESPONSE,
    has_formatting_issues,
    validate_response,
)


class TestEmailTemplateFormatting(unittest.TestCase):
    """Test suite for ShopiFyX Plain-Text Email Standardization & Validation Pipeline."""

    # 1. Simple product question
    def test_01_simple_product_question(self):
        context = ["AeroRun Running Shoes feature breathable engineered mesh and an EVA foam cushioned midsole. Priced at $120."]
        raw_llm = (
            "Hi Alice,\n\n"
            "Thank you for reaching out about our AeroRun Running Shoes.\n\n"
            "The shoes feature breathable engineered mesh and an EVA foam cushioned midsole for optimal comfort.\n\n"
            "Best regards,\nCustomer Support Team\nShopiFyX"
        )
        cleaned = normalize_customer_response(raw_llm, customer_name="Alice")
        val = validate_email_response(cleaned, context, intent="product_inquiry", emotion="neutral")
        
        self.assertTrue(val["valid"])
        self.assertTrue(cleaned.startswith("Hi Alice,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))
        self.assertIn("breathable engineered mesh", cleaned.lower())
        self.assertNotIn("**", cleaned)
        self.assertNotIn("##", cleaned)
        self.assertNotIn("•", cleaned)

    # 2. Order-status question
    def test_02_order_status_question(self):
        context = ["Standard delivery takes 3-5 business days. Once shipped, tracking details are sent via email."]
        raw_llm = (
            "**Order Status Update**\n\n"
            "Your package has been dispatched.\n\n"
            "- Standard delivery takes 3-5 business days.\n"
            "- Tracking details will be emailed directly to you.\n\n"
            "Best regards,\nShopiFyX Team"
        )
        cleaned = normalize_customer_response(raw_llm, customer_name="Bob Smith")
        val = validate_email_response(cleaned, context, intent="order_status", emotion="neutral")
        
        self.assertTrue(val["valid"])
        self.assertTrue(cleaned.startswith("Hi Bob,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))
        self.assertNotIn("**", cleaned)
        self.assertNotIn("- ", cleaned)

    # 3. Refund request
    def test_03_refund_request(self):
        context = ["Refunds are processed within 5-7 business days to the original payment method once the returned item is inspected."]
        raw_llm = (
            "Hi Carol,\n\n"
            "### Refund Policy Details\n"
            "Thank you for contacting us regarding your refund request.\n\n"
            "Refunds are processed within 5-7 business days to the original payment method once the returned item is inspected."
        )
        cleaned = normalize_customer_response(raw_llm, customer_name="Carol")
        val = validate_email_response(cleaned, context, intent="refund_request", emotion="neutral")
        
        self.assertTrue(val["valid"])
        self.assertTrue(cleaned.startswith("Hi Carol,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))
        self.assertIn("5-7 business days", cleaned)
        self.assertNotIn("###", cleaned)

    # 4. Return request
    def test_04_return_request(self):
        context = ["ShopiFyX allows returns within 7 days of delivery. Items must be unused, in original packaging with invoice."]
        raw_llm = (
            "Hi David,\n\n"
            "Thank you for reaching out regarding your return request.\n\n"
            "ShopiFyX allows returns within 7 days of delivery. Items must be unused, in original packaging with invoice.\n\n"
            "Best regards,\nSupport"
        )
        cleaned = normalize_customer_response(raw_llm, customer_name="David")
        val = validate_email_response(cleaned, context, intent="return_request", emotion="neutral")
        
        self.assertTrue(val["valid"])
        self.assertTrue(cleaned.startswith("Hi David,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))
        self.assertIn("7 days", cleaned)
        self.assertNotIn("*", cleaned)

    # 5. Warranty question
    def test_05_warranty_question(self):
        context = ["ShopiFyX offers a 1-year limited warranty covering manufacturing defects from date of delivery."]
        raw_llm = (
            "All electronic purchases include standard warranty protection.\n\n"
            "ShopiFyX offers a 1-year limited warranty covering manufacturing defects from date of delivery."
        )
        cleaned = normalize_customer_response(raw_llm, customer_name="Eva")
        val = validate_email_response(cleaned, context, intent="warranty_inquiry", emotion="neutral")
        
        self.assertTrue(val["valid"])
        self.assertTrue(cleaned.startswith("Hi Eva,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))
        self.assertIn("1-year", cleaned)

    # 6. Angry customer
    def test_06_angry_customer(self):
        context = ["Orders delayed due to weather or transit disruptions will be expedited. Contact support with Order ID."]
        fallback = _fallback_reply(
            strategy="empathy_first",
            intent="complaint",
            emotion="angry",
            context_docs=context,
        )
        cleaned = normalize_customer_response(fallback, customer_name="Frank")
        
        self.assertTrue(cleaned.startswith("Hi Frank,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))
        self.assertIn("frustration", cleaned.lower())

    # 7. Follow-up email using "it" / "that" / "same issue"
    def test_07_follow_up_with_pronouns(self):
        memory = CustomerMemory(
            profile=CustomerProfile(customer_id="cust-7", email="grace@example.com", name="Grace Hopper"),
            open_issues=[
                CustomerIssue(id="iss-1", customer_id="cust-7", issue_title="Charged twice for Order SFX-990", status="open")
            ],
            is_empty=False,
        )
        context = ["Duplicate charges on UPI/Cards are auto-reversed within 24-48 hours. Bank processing may take 3-5 business days."]
        fallback = _fallback_reply(
            strategy="status_update",
            intent="refund_status",
            emotion="frustrated",
            context_docs=context,
            customer_memory=memory,
        )
        cleaned = normalize_customer_response(fallback, customer_name="Grace Hopper")
        
        self.assertTrue(cleaned.startswith("Hi Grace,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))
        self.assertIn("charged twice", cleaned.lower())

    # 8. Customer with previous conversation history
    def test_08_customer_with_conversation_history(self):
        context = ["Returns must be packed securely in original packaging with invoice attached."]
        raw_llm = (
            "Hi Hank,\n\n"
            "Following up on our earlier conversation regarding your return request.\n\n"
            "Returns must be packed securely in original packaging with invoice attached.\n\n"
            "Best regards,\nCustomer Support Team"
        )
        cleaned = normalize_customer_response(raw_llm, customer_name="Hank")
        val = validate_email_response(cleaned, context, intent="return_instructions", emotion="neutral")
        
        self.assertTrue(val["valid"])
        self.assertTrue(cleaned.startswith("Hi Hank,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))

    # 9. Transactional action successfully initiated
    def test_09_transactional_action_initiated(self):
        context = ["Doorstep pickup for exchange will be arranged within 2-3 business days. Delivery agent inspects item on spot."]
        raw_response = (
            "Hi Ivy,\n\n"
            "We have initiated your size exchange request for Order SFX-4412.\n\n"
            "Doorstep pickup for exchange will be arranged within 2-3 business days. Delivery agent inspects item on spot.\n\n"
            "Best regards,\nCustomer Support Team\nShopiFyX"
        )
        cleaned = normalize_customer_response(raw_response, customer_name="Ivy")
        val = validate_email_response(cleaned, context, intent="exchange_request", emotion="neutral")
        
        self.assertTrue(val["valid"])
        self.assertTrue(cleaned.startswith("Hi Ivy,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))

    # 10. Transactional action rejected / policy limitation
    def test_10_transactional_action_rejected(self):
        context = ["Items marked as Clearance Sale or opened personal care items are strictly non-returnable."]
        raw_response = (
            "Hi Jack,\n\n"
            "Thank you for contacting ShopiFyX.\n\n"
            "Items marked as Clearance Sale or opened personal care items are strictly non-returnable.\n\n"
            "Please let us know if you have any questions regarding other eligible items.\n\n"
            "Best regards,\nCustomer Support Team\nShopiFyX"
        )
        cleaned = normalize_customer_response(raw_response, customer_name="Jack")
        val = validate_email_response(cleaned, context, intent="return_request", emotion="neutral")
        
        self.assertTrue(val["valid"])
        self.assertTrue(cleaned.startswith("Hi Jack,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))

    # 11. Escalation response / missing KB
    def test_11_escalation_response_missing_context(self):
        fallback = normalize_customer_response(SAFE_FALLBACK_RESPONSE, customer_name="Karen")
        
        self.assertTrue(fallback.startswith("Hi Karen,"))
        self.assertTrue(fallback.endswith(STANDARD_CLOSING))
        self.assertIn("reviewing your request", fallback)
        self.assertNotIn("memory", fallback.lower())
        self.assertNotIn("rag", fallback.lower())

    # 12. Missing customer name (Greeting strictly 'Hi,')
    def test_12_missing_customer_name(self):
        raw = "We have received your message and will check the delivery status."
        
        for empty_name in ["", "   ", "Valued Customer", "Customer", "none", "None", "null"]:
            cleaned = normalize_customer_response(raw, customer_name=empty_name)
            self.assertTrue(cleaned.startswith("Hi,\n\n"), f"Failed for name '{empty_name}': starts with {cleaned[:20]}")
            self.assertNotIn("Valued Customer", cleaned)
            self.assertNotIn("Dear", cleaned)
            self.assertTrue(cleaned.endswith(STANDARD_CLOSING))

    # 13. Response containing Markdown generated by LLM
    def test_13_response_containing_markdown(self):
        raw = (
            "Hi Leo,\n\n"
            "### Delivery Updates\n\n"
            "Your **Order SFX-771** has shipped via **Express Courier**.\n\n"
            "**Next Steps:**\n"
            "* Wait 2-3 business days for delivery.\n"
            "* Track your package online at tracking link.\n\n"
            "Best regards,\nCustomer Support Team"
        )
        cleaned = normalize_customer_response(raw, customer_name="Leo")
        
        self.assertNotIn("**", cleaned)
        self.assertNotIn("###", cleaned)
        self.assertNotIn("* ", cleaned)
        self.assertFalse(has_formatting_issues(cleaned)[0])
        self.assertTrue(cleaned.startswith("Hi Leo,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))

    # 14. Response containing excessive blank lines
    def test_14_response_excessive_blank_lines(self):
        raw = (
            "Hi Mia,\n\n\n\n\n"
            "Thank you for contacting us.\n\n\n\n\n"
            "Your return has been processed.\n\n\n\n\n"
            "Best regards,\nCustomer Support Team"
        )
        cleaned = normalize_customer_response(raw, customer_name="Mia")
        
        self.assertNotIn("\n\n\n", cleaned)
        self.assertTrue(cleaned.startswith("Hi Mia,\n\nThank you for contacting us.\n\nYour return has been processed."))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))

    # 15. Response containing "Here is your response:" preamble
    def test_15_response_containing_preamble(self):
        raw = (
            "Here is your response:\n\n"
            "Hi Noah,\n\n"
            "Thank you for contacting ShopiFyX support.\n\n"
            "We have updated your shipping address for Order SFX-901.\n\n"
            "Best regards,\nCustomer Support Team\nShopiFyX"
        )
        cleaned = normalize_customer_response(raw, customer_name="Noah")
        
        self.assertNotIn("Here is your response", cleaned)
        self.assertTrue(cleaned.startswith("Hi Noah,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))

    # 16. Duplicate greeting and sign-off
    def test_16_duplicate_greeting_and_signoff(self):
        raw = (
            "Hi Olivia,\n\n"
            "Hi Olivia,\n\n"
            "Thank you for reaching out.\n\n"
            "Your order will arrive on Monday.\n\n"
            "Best regards,\n"
            "Customer Support Team\n"
            "ShopiFyX\n\n"
            "Best regards,\n"
            "ShopiFyX Support Team"
        )
        cleaned = normalize_customer_response(raw, customer_name="Olivia")
        
        self.assertEqual(cleaned.count("Hi Olivia,"), 1)
        self.assertEqual(cleaned.count("Best regards,"), 1)
        self.assertEqual(cleaned.count("Customer Support Team"), 1)
        self.assertTrue(cleaned.startswith("Hi Olivia,"))
        self.assertTrue(cleaned.endswith(STANDARD_CLOSING))


if __name__ == "__main__":
    unittest.main()
